BROWSER_HEADERS = {
    "Accept": "application/json",
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64)"
}  # Required to avoid 403 response (thank you thorn)

BALANCE_TYPE_PARAMETERS = [
    "annualStockholdersEquity",
    "annualPrepaidAssets",
    "annualCashAndCashEquivalents",
    "annualInvestmentinFinancialAssets",
    "annualGoodwillAndOtherIntangibleAssets",
    "annualAdditionalPaidInCapital",
    "annualTotalTaxPayable",
    "annualCommonStockEquity",
    "annualCashFinancial",
    "annualTangibleBookValue",
    "annualShareIssued",
    "annualCapitalStock",
    "annualOtherPayable",
    "annualCurrentAssets",
    "annualTotalCapitalization",
    "annualCurrentLiabilities",
    "annualNetPPE",
    "annualMachineryFurnitureEquipment",
    "annualAccumulatedDepreciation",
    "annualOtherShortTermInvestments",
    "annualTreasuryStock",
    "annualTreasurySharesNumber",
    "annualFinancialAssetsDesignatedasFairValueThroughProfitorLossTotal",
    "annualDividendsPayable",
    "annualRetainedEarnings",
    "annualCommonStock",
    "annualOrdinarySharesNumber",
    "annualWorkingCapital",
    "annualAssetsHeldForSaleCurrent",
    "annualTaxesReceivable",
    "annualTotalLiabilitiesNetMinorityInterest",
    "annualCashCashEquivalentsAndShortTermInvestments",
    "annualTotalAssets",
    "annualInvestedCapital",
    "annualPayables",
    "annualAccountsPayable",
    "annualRestrictedCash",
    "annualTotalEquityGrossMinorityInterest",
    "annualTotalNonCurrentAssets",
    "annualGrossPPE",
    "annualOtherReceivables",
    "annualNetTangibleAssets",
    "annualReceivables",
    "annualLongTermDebt",
    "annualTotalDebt",
    "annualGoodwill",
    "annualFinancialAssets",
    "annualAccountsReceivable",
    "annualPreferredStock",
    "annualNetDebt",
    "annualCashEquivalents",
    "annualCurrentDebt",
]

INCOME_TYPE_PARAMETERS = [
    "TotalRevenue",
    "CostOfRevenue",
    "GrossProfit",
    "OperatingExpense",
    "EBIT",
    "EBITDA",
    "NetIncome",
    "NetIncomeCommonStockholders",
    "OperatingRevenue",
    "ResearchAndDevelopment",
    "Amortization",
    "OperatingIncome",
    "TotalExpenses",
    "BasicEPS",
    "BasicAverageShares",
]

CASHFLOW_TYPE_PARAMETERS = [
    "FreeCashFlow",
#    "OtherNonCashItems",
#    "InvestingCashFlow",
#    "LongTermDebtIssuance",
#    "InterestReceivedCFI",
#    "DepreciationAndAmortization",
#    "OperatingCashFlow",
#    "PurchaseOfInvestment",
#    "StockBasedCompensation",
#    "NetIncomeFromContinuingOperations",
#    "SaleOfInvestment",
#    "Depreciation",
#    "CommonStockPayments",
#    "ChangeInReceivables",
#    "NetCommonStockIssuance",
#    "ChangeInWorkingCapital",
#    "NetInvestmentPurchaseAndSale",
#    "EffectOfExchangeRateChanges",
#    "GainLossOnSaleOfPPE",
#    "CashDividendsPaid",
#    "BeginningCashPosition",
#    "PurchaseOfPPE",
#    "LongTermDebtPayments",
#    "IssuanceOfDebt",
#    "OtherCashAdjustmentOutsideChangeinCash",
#    "FinancingCashFlow",
#    "GainLossOnInvestmentSecurities",
#    "RepurchaseOfCapitalStock",
#    "SaleOfBusiness",
#    "CapitalExpenditure",
#    "NetIssuancePaymentsOfDebt",
#    "NetIntangiblesPurchaseAndSale",
#    "CommonStockIssuance",
#    "RepaymentOfDebt",
#    "NetBusinessPurchaseAndSale",
#    "DividendsReceivedCFI",
#    "ChangesInCash",
#    "IssuanceOfCapitalStock",
#    "NetForeignCurrencyExchangeGainLoss",
#    "NetOtherInvestingChanges",
#    "NetLongTermDebtIssuance",
#    "PurchaseOfIntangibles",
#    "ChangeInPayable",
#    "EndCashPosition",
#    "ChangeInOtherCurrentAssets",
#    "CommonStockDividendPaid",
#    "NetPPEPurchaseAndSale",
#    "SaleOfPPE",
#    "TaxesRefundPaid",
#    "Depletion",
#    "ProceedsFromStockOptionExercised",
#    "ChangeInInterestPayable",
#    "CashFlowFromContinuingInvestingActivities",
#    "ShortTermDebtPayments",
#    "DividendPaidCFO",
#    "PurchaseOfBusiness",
#    "PaymentsonBehalfofEmployees",
#    "InterestPaidCFF",
#    "SaleOfIntangibles",
#    "TaxesRefundPaidDirect",
#    "PensionAndEmployeeBenefitExpense",
#    "CashFromDiscontinuedOperatingActivities",
#    "ChangeInPrepaidAssets",
#    "PaymentstoSuppliersforGoodsandServices",
#    "DomesticSales",
#    "InterestPaidCFO",
#    "NetShortTermDebtIssuance",
#    "ClassesofCashPayments",
#    "SaleOfInvestmentProperties",
#    "DividendReceivedCFO",
#    "OtherCashPaymentsfromOperatingActivities",
#    "PreferredStockDividendPaid",
#    "ChangeInAccruedExpense",
#    "CashFlowFromDiscontinuedOperation",
#    "ChangeInPayablesAndAccruedExpense",
#    "CashFlowFromContinuingOperatingActivities",
#    "AdjustedGeographySegmentData",
#    "OtherCashReceiptsfromOperatingActivities",
#    "NetPreferredStockIssuance",
#    "CapitalExpenditureReported",
#    "AmortizationCashFlow",
#    "ChangeInAccountPayable",
#    "DividendsPaidDirect",
#    "OperatingGainsLosses",
#    "UnrealizedGainLossOnInvestmentSecurities",
#    "AssetImpairmentCharge",
#    "ChangeInInventory",
#    "ExcessTaxBenefitFromStockBasedCompensation",
#    "PreferredStockPayments",
#    "ForeignSales",
#    "PurchaseOfInvestmentProperties",
#    "ShortTermDebtIssuance",
#    "AmortizationOfIntangibles",
#    "ReceiptsfromGovernmentGrants",
#    "ChangesInAccountReceivables",
#    "PreferredStockIssuance",
#    "CashFromDiscontinuedFinancingActivities",
#    "InterestReceivedCFO",
#    "IncomeTaxPaidSupplementalData",
#    "NetOtherFinancingCharges",
#    "ChangeInTaxPayable",
#    "ChangeInOtherCurrentLiabilities",
#    "ChangeInIncomeTaxPayable",
#    "CashFlowsfromusedinOperatingActivitiesDirect",
#    "InterestPaidDirect",
#    "ClassesofCashReceiptsfromOperatingActivities",
#    "ProvisionandWriteOffofAssets",
#    "EarningsLossesFromEquityInvestments",
#    "GainLossOnSaleOfBusiness",
#    "ChangeInDividendPayable",
#    "DeferredIncomeTax",
#    "DividendsReceivedDirect",
#    "AmortizationOfSecurities",
#    "CashFlowFromContinuingFinancingActivities",
#    "OtherCashAdjustmentInsideChangeinCash",
#    "InterestReceivedDirect",
#    "NetInvestmentPropertiesPurchaseAndSale",
#    "CashFromDiscontinuedInvestingActivities",
#    "DepreciationAmortizationDepletion",
#    "ChangeInOtherWorkingCapital",
#    "ReceiptsfromCustomers",
]

COMPANY_TYPE_PARAMETERS = []

OWNERSHIP_TYPE_PARAMETERS = []